services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KimaiPlugin\DeductionTimeBundle\:
        resource: '../../*'
        exclude: '../../{Resources,.github}'
